version: "3"

services:
  persistence:
    build:
      context: ./database
      dockerfile: Dockerfile
    volumes:
      - pgdata:/var/lib/postgresql/data
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - persistence
    ports:
      - "3001:3001"
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      - server
    ports:
      - "3000:3000"

volumes:
  pgdata:
